ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AceJobAgency.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace AceJobAgency.ViewModels
{
    public class Register
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string NRIC { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public string DOB { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public string Resume { get; set; }

        [Required]
        public string Whoami { get; set; }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AceJobAgency.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using AceJobAgency.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Login.cshtml.cs
using AceJobAgency.Model;
using AceJobAgency.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace AceJobAgency.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<ApplicationUser> signInManager;
        public LoginModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                LModel.RememberMe, lockoutOnFailure: true);
                if (identityResult.Succeeded)
                {
                    //Create the security context
                    var claims = new List<Claim> {
                        new Claim(ClaimTypes.Name, "c@c.com"),
                        new Claim(ClaimTypes.Email, "c@c.com")
                    };
                    var i = new ClaimsIdentity(claims, "MyCookieAuth");
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(i);
                    await HttpContext.SignInAsync("MyCookieAuth", claimsPrincipal);

                    return RedirectToPage("Index");
                }

                else if (identityResult.IsLockedOut) {
					ModelState.AddModelError("", "Account is locked out");
				}
                else
                {
					ModelState.AddModelError("", "Username or Password incorrect");
				}
			}
            return Page();
        }

    }
}

Pages/Logout.cshtml.cs
using AceJobAgency.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class LogoutModel : PageModel
    {

        private readonly SignInManager<ApplicationUser> signInManager;
        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Register.cshtml.cs
using AceJobAgency.Model;
using AceJobAgency.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages.Shared
{
	public interface IDataProtector : Microsoft.AspNetCore.DataProtection.IDataProtectionProvider
    {
    }

	public class RegisterModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }
		private readonly RoleManager<IdentityRole> roleManager;


		[BindProperty]
        public Register RModel { get; set; }
        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;

	}
	public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");
                var user = new ApplicationUser()
                {
                    UserName = RModel.Email,
                    Email = RModel.Email,
                    FirstName = RModel.FirstName,
                    LastName = RModel.LastName,
                    Gender = RModel.Gender,
                    NRIC = protector.Protect(RModel.NRIC),
                    DOB = RModel.DOB,
                    Resume = RModel.Resume,
                    Whoami = RModel.Whoami
                };
				IdentityRole role = await roleManager.FindByIdAsync("Admin");
				if (role == null)
				{
					IdentityResult result2 = await roleManager.CreateAsync(new IdentityRole("Admin"));
					if (!result2.Succeeded)
					{
						ModelState.AddModelError("", "Create role admin failed");
					}
				}
				var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
					result = await userManager.AddToRoleAsync(user, "Admin");

					await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();

        }
    }
}

Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Http
@model IndexModel
@{
    ViewData["Home"] = "Home page";
}


<div class="text-center">
    <h1 class="display-4">Ace Job Agency</h1>
    <p>Ace Job Agency</a>.</p>
</div>

Pages/Login.cshtml
@page
@model AceJobAgency.Pages.LoginModel
@{
}
<script src="https://www.google.com/recaptcha/api.js"></script>


<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>
			<div asp-validation-summary="All" class="text-danger"></div>

			<form method="post">
				
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button class="g-recaptcha"
@*							data-sitekey="6LefmF0kAAAAAL8CbxH44eC9_hw4hPmF7lc0sW0L"
							data-callback='onSubmit'
							data-action='submit'*@>
						Submit
					</button>
				</div>

			</form>
		</div>
	</div>
</div>

<script>
	function onSubmit(token) {
		document.getElementById("demo-form").submit();
	}
</script>

Pages/Logout.cshtml
@page
@model AceJobAgency.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

Pages/Profile.cshtml
@page
@model AceJobAgency.Pages.ProfileModel
@{
}

Pages/Register.cshtml
@page
@model AceJobAgency.Pages.Shared.RegisterModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post" asp-antiforgery="true">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FirstName">First Name</label>
					<input type="Text" asp-for="RModel.FirstName" class="form-control" />
					<span asp-validaton-for="RModel.FirstName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.LastName">Last Name</label>
					<input type="Text" asp-for="RModel.LastName" class="form-control" />
					<span asp-validaton-for="RModel.LastName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Gender">Gender</label><br />
					@*<input type="radio" asp-for="RModel.Gender" value="Male" name="Gender" id="Gender" />
					<label for="Male">Male</label>				
					<input type="radio" asp-for="RModel.Gender" value="Female" name="Gender" id="Gender" />
					<label for="Female">Female</label><br />*@
					<input type="Text" asp-for="RModel.Gender" class="form-control" />
					<span asp-validaton-for="RModel.Gender" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.NRIC">NRIC</label>
					<input type="Text" asp-for="RModel.NRIC" class="form-control" />
					<span asp-validaton-for="RModel.NRIC" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Email">Email Address</label>
					<input type="Text" asp-for="RModel.Email" class="form-control" />
					<span asp-validaton-for="RModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
					<input type="password" asp-for="RModel.Password" class="form-control" />
					<span asp-validaton-for="RModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
					<input type="password" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.DOB">Date of Birth</label>
					<input type="date" asp-for="RModel.DOB" class="form-control" />
					<span asp-validaton-for="RModel.DOB" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Resume">Resume</label>
					<input type="file" asp-for="RModel.Resume" class="form-control" 
					accept="application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document" />
					<span asp-validaton-for="RModel.Resume" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Whoami">Whoami</label>
					<input type="Text" asp-for="RModel.Whoami" class="form-control" />
					<span asp-validaton-for="RModel.Whoami" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>

Pages/Shared/_Layout.cshtml
@using AceJobAgency.Model
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Home"] - AceJobAgency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AceJobAgency.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AceJobAgency</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    @{
                        if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav d-flex justify-content-end">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                            //<ul class="navbar-nav flex-grow-1 justify-content-end">
                            //    <li class="nav-item">
                            //        <a class="nav-link text-dark" asp-area="" asp-page="/register">Register</a>
                            //    </li>
                            //    <li class="nav-item">
                            //        <a class="nav-link text-dark" asp-area="" asp-page="/login">Login</a>
                            //    </li>
                            //</ul>
                        }

                        else
                        {
                            <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Register">Register</a>
                                </li>
                            </ul>
                        }

                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AceJobAgency - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>